//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satisotomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori_Urun
    {
        public int Id { get; set; }
        public Nullable<int> Kategori_id { get; set; }
        public Nullable<int> Urun_id { get; set; }
    }
}
