//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satisotomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string Aciklamasi { get; set; }
        public string Barkod { get; set; }
    }
}
